services:
  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=catsgram
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10


  db-init:
    image: postgres:16.1
    container_name: db-init
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        set -e
        psql postgresql://dbuser:12345@db:5432/catsgram -v ON_ERROR_STOP=1 <<-EOSQL
          CREATE TABLE IF NOT EXISTS users (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            username VARCHAR(40) NOT NULL,
            email VARCHAR(255) NOT NULL,
            password VARCHAR(40) NOT NULL,
            registration_date TIMESTAMP WITH TIME ZONE NOT NULL
          );
        
          CREATE TABLE IF NOT EXISTS posts (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            author_id BIGINT NOT NULL REFERENCES users(id),
            description TEXT,
            post_date TIMESTAMP WITH TIME ZONE NOT NULL
          );
        
          CREATE TABLE IF NOT EXISTS comments (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            author_id BIGINT NOT NULL REFERENCES users(id),
            post_id BIGINT NOT NULL REFERENCES posts(id),
            text TEXT,
            creation_date TIMESTAMP WITH TIME ZONE NOT NULL
          );
        
          CREATE TABLE IF NOT EXISTS likes (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id),
            post_id BIGINT NOT NULL REFERENCES posts(id)
          );
        
          CREATE TABLE IF NOT EXISTS image_storage (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            original_name VARCHAR(255),
            file_path VARCHAR(1024),
            post_id BIGINT NOT NULL REFERENCES posts(id)
          );
        EOSQL